server:
  port: 8080
spring:
  application:
    name: 251210_thymeleaf
  # ???? ??? (application-dev.yaml/yml)
  profiles:
    active: dev
  # DB ?? (dev?? ???)
  # View Resolver & Template Engine
  thymeleaf:
    # ?? ?????? ????? ???? thymeleaf? ??? ? ???? ??????
    # ?? ???? ?? return. -> ??????? off(false).
    cache: false
    # prefix: classpath:/templates/
    # suffix: .html
    # default(???)?? ??